version: '2'
services:
  csrs1:
    image: mongo
    volumes:
      - /home/work/dbdata/mongo/cs/rs1:/data/db
    command: mongod --noauth --bind_ip_all --configsvr --replSet csrs --dbpath /data/db
  csrs2:
    image: mongo
    volumes:
      - /home/work/dbdata/mongo/cs/rs2:/data/db
    command: mongod --noauth --bind_ip_all --configsvr --replSet csrs --dbpath /data/db
  csrs3:
    image: mongo
    volumes:
      - /home/work/dbdata/mongo/cs/rs3:/data/db
    command: mongod --noauth --bind_ip_all --configsvr --replSet csrs --dbpath /data/db

  shrs1:
    image: mongo
    volumes:
      - /home/work/dbdata/mongo/sh/rs1:/data/db
    command: mongod --noauth --bind_ip_all --dbpath /data/db --shardsvr --replSet shrs
  shrs2:
    image: mongo
    volumes:
      - /home/work/dbdata/mongo/sh/rs2:/data/db
    command: mongod --noauth --bind_ip_all --dbpath /data/db --shardsvr --replSet shrs
  shrs3:
    image: mongo
    volumes:
      - /home/work/dbdata/mongo/sh/rs3:/data/db
    command: mongod --noauth --bind_ip_all --dbpath /data/db --shardsvr --replSet shrs
  mongo:
    image: mongo
    command: mongos --noauth --bind_ip_all --configdb csrs/csrs1:27019,csrs2:27019,csrs3:27019